module.exports = {
  'kidney disease': 'nephrologist',
  'kidney': 'nephrologist',
  'liver disease': 'hepatologist',
  'liver': 'hepatologist',
  'heart': 'cardiologist',
  'chest pain': 'cardiologist',
  'hypertension': 'cardiologist',
  'high blood pressure': 'cardiologist',
  'diabetes': 'endocrinologist',
  'blood sugar': 'endocrinologist',
  'pregnancy': 'obstetrician',
  'maternal': 'obstetrician',
  'antenatal': 'obstetrician',
  'mental health': 'psychiatrist',
  'depression': 'psychiatrist',
  'anxiety': 'psychiatrist',
  'cancer': 'oncologist',
  'tumor': 'oncologist',
  'malaria': 'general practitioner',
  'typhoid': 'general practitioner',
  'skin': 'dermatologist',
  'rash': 'dermatologist',
  'eye': 'ophthalmologist',
  'bone': 'orthopedist',
  'joint': 'orthopedist',
  'child': 'paediatrician',
  'infant': 'paediatrician',
  'teeth': 'dentist',
  'default': 'general practitioner',
};
